### ISSUE TITLE
tagging for new version

### ISSUE THREAD

**Issue by wookay** [JuliaLang/ZMQ.jl#108]
would you mind tagging it for the newer version into METADATA.jl
(related on fixing `bytestring` deprecation)
thanks.

**Comment by jmbromley** [comment]
Tagging this in METADATA has resulted in Julia 0.4.6 pulling in the new bytestring deprecation when installing IJulia.  This makes using jupyter notebook an extremely uncomfortable experience (JuliaLang/IJulia.jl#443), and it seems a little premature given Julia itself is not deprecating bytestring until 0.5.  Is there anyway to label this release as for Julia >= 0.5 only, so that IJulia doesn't start covering the notebooks of Julia 0.4 users with warnings (it's triggering 14 warnings for even simple cell evaluations)?

**Comment by wookay** [comment]
I'm sorry to give the bad experience for you.
having `Pkg.pin("ZMQ",v"0.3.2")` for a while, as you said that.
I have PR for this https://github.com/JuliaLang/IJulia.jl/pull/444

**Comment by tkelman** [comment]
I think we should also make the deprecation only apply for versions of Julia where `bytestring` is itself deprecated. Otherwise since ZMQ still supports Julia 0.3 but IJulia does not with its newest versions, this warning would apply for anyone still using IJulia in Julia 0.3 as well.

**Comment by wookay** [comment]
(urgent) PR
https://github.com/JuliaLang/ZMQ.jl/pull/109

**Comment by jmbromley** [comment]
Thankyou wookay and tkelman for fixing this so quickly!  I can confirm no more warnings with Julia 0.4 and ZMQ from master.
